import { useEffect, useMemo, useState } from "react";
import { ChevronLeft, ChevronRight, X } from "lucide-react";
import { useLocation } from "react-router-dom";
import { useAuth } from "../auth/AuthContext";

const commonSteps = [
  {
    target: "main-nav",
    title: "Navigation Bar",
    body: "Use these tabs to move between live status, usage history, device control, billing, and the assistant.",
  },
  {
    target: "user-menu",
    title: "Your Account",
    body: "Your user profile and logout action are here.",
  },
];

const pageIntroSteps = {
  "/": {
    target: "page-overview",
    title: "Dashboard Overview",
    body: "This is your main dashboard. It includes the live energy status chart, current grid and solar power, bill savings, eco impact, usage by source, and top energy consumers.",
  },
  "/analytics": {
    target: "page-overview",
    title: "Usage History Overview",
    body: "This page shows historical grid and solar data so you can compare usage patterns over time.",
  },
  "/devices": {
    target: "page-overview",
    title: "Smart Control Overview",
    body: "This page lets you monitor appliances, see running devices, and control selected units.",
  },
  "/billing": {
    target: "page-overview",
    title: "Billing Overview",
    body: "This page explains your generated bill, payable amount, solar savings, and budget status.",
  },
  "/chat": {
    target: "page-overview",
    title: "Assistant Overview",
    body: "This page gives you both a conversational Chat Bot and a guide-based Q&A Bot in one place.",
  },
};

const pageSteps = {
  "/": [
    {
      target: "page-heading",
      title: "Dashboard",
      body: "Start here for the live status of grid power, solar power, savings, and eco impact.",
    },
    {
      target: "dashboard-flow",
      title: "Today's Energy Flow",
      body: "This chart compares grid power and solar power through the day. The dashed lines make both signals visible when they overlap.",
    },
    {
      target: "dashboard-metrics",
      title: "Live Metrics",
      body: "These cards summarize the current grid draw, solar generation, energy balance, bill savings, and CO2 impact.",
    },
    {
      target: "dashboard-insights",
      title: "Usage And Device Insights",
      body: "This section shows grid versus solar usage in kWh and lists the devices consuming the most power.",
    },
  ],
  "/analytics": [
    {
      target: "page-heading",
      title: "Usage History",
      body: "This page explains historical grid consumption and solar generation.",
    },
    {
      target: "history-filters",
      title: "Period Filters",
      body: "Switch between daily, weekly, and monthly views to compare usage over time.",
    },
    {
      target: "history-summary",
      title: "History Summary",
      body: "These cards show total grid use, solar generated, solar coverage, and the peak grid period.",
    },
    {
      target: "history-chart",
      title: "Energy Chart",
      body: "Use this chart to compare energy consumed from the grid versus energy generated by solar.",
    },
  ],
  "/devices": [
    {
      target: "page-heading",
      title: "Smart Control",
      body: "This page helps you monitor appliances and control selected devices.",
    },
    {
      target: "device-stats",
      title: "Device Status",
      body: "These cards show how many devices are active and the current load in watts.",
    },
    {
      target: "device-controls",
      title: "Control Modes",
      body: "Filter device groups, apply seasonal modes, or add a new device here.",
    },
    {
      target: "device-list",
      title: "Device Cards",
      body: "Each card shows running units, location, power usage, and quick controls.",
    },
  ],
  "/billing": [
    {
      target: "page-heading",
      title: "Billing",
      body: "This page connects energy usage to bill generation, savings, and budget status.",
    },
    {
      target: "billing-alert",
      title: "Budget Status",
      body: "This message quickly tells you whether solar savings or controlled grid usage is keeping the payable bill in budget.",
    },
    {
      target: "billing-panels",
      title: "Bill Details",
      body: "Review generated bill, payable bill, solar credit, budget limit, and invoice history.",
    },
  ],
  "/chat": [
    {
      target: "page-heading",
      title: "Assistant",
      body: "Use Chat Bot for conversational help and switch to Q&A Bot when you want guide-based answers.",
    },
    {
      target: "chat-panel",
      title: "Chat Area",
      body: "Type your question here. The selected toggle decides whether the request goes to Chat Bot or Q&A Bot.",
    },
    {
      target: "chat-suggestions",
      title: "Suggested Questions",
      body: "Use these prompts when you want quick examples to test the current bot mode.",
    },
  ],
};

function getPlacement(rect) {
  const tooltipWidth = Math.min(420, window.innerWidth - 32);
  const left = Math.min(
    Math.max(16, rect.left + rect.width / 2 - tooltipWidth / 2),
    window.innerWidth - tooltipWidth - 16
  );
  const belowTop = rect.bottom + 18;
  const top = belowTop + 220 < window.innerHeight ? belowTop : Math.max(16, rect.top - 238);

  return { left, top, width: tooltipWidth };
}

export default function GuidedTour() {
  const { user, completePageTour, dismissTour } = useAuth();
  const location = useLocation();
  const [stepIndex, setStepIndex] = useState(0);
  const [targetRect, setTargetRect] = useState(null);
  const hasSeenCurrentPage = Boolean(user?.seenTours?.[location.pathname]);
  const isTourPending = user?.tourPending ?? (user?.hasSeenIntro === false);
  const shouldShow = Boolean(
    user && isTourPending && !user.tourDismissed && !hasSeenCurrentPage
  );
  const steps = useMemo(
    () => [
      pageIntroSteps[location.pathname] ?? pageIntroSteps["/"],
      ...(location.pathname === "/" ? commonSteps : []),
      ...(pageSteps[location.pathname] ?? pageSteps["/"]),
    ],
    [location.pathname]
  );
  const step = steps[stepIndex] ?? steps[0];

  useEffect(() => {
    setStepIndex(0);
  }, [location.pathname]);

  useEffect(() => {
    if (!shouldShow || !step) return undefined;

    let frameId;
    const updateRect = () => {
      const target = document.querySelector(`[data-tour="${step.target}"]`);
      if (!target) {
        setTargetRect(null);
        return;
      }

      target.scrollIntoView({ behavior: "smooth", block: "center", inline: "center" });
      frameId = window.requestAnimationFrame(() => {
        const rect = target.getBoundingClientRect();
        setTargetRect({
          top: rect.top,
          left: rect.left,
          width: rect.width,
          height: rect.height,
          bottom: rect.bottom,
        });
      });
    };

    const timer = window.setTimeout(updateRect, 160);
    window.addEventListener("resize", updateRect);
    window.addEventListener("scroll", updateRect, true);

    return () => {
      window.clearTimeout(timer);
      window.cancelAnimationFrame(frameId);
      window.removeEventListener("resize", updateRect);
      window.removeEventListener("scroll", updateRect, true);
    };
  }, [shouldShow, step]);

  if (!shouldShow || !step) return null;

  const viewportWidth = window.innerWidth;
  const viewportHeight = window.innerHeight;
  const isPageOverview = step.target === "page-overview";
  const highlight = targetRect
    ? (() => {
        const top = Math.max(8, targetRect.top - 8);
        const left = Math.max(8, targetRect.left - 8);
        const width = isPageOverview
          ? viewportWidth - (left * 2)
          : Math.min(viewportWidth - left - 8, targetRect.width + 16);
        const visibleBottom = Math.min(viewportHeight - 8, targetRect.bottom + 8);
        const height = isPageOverview
          ? Math.max(260, viewportHeight - top - 16)
          : Math.max(96, Math.min(targetRect.height + 16, visibleBottom - top));

        return { top, left, width, height };
      })()
    : {
        top: 120,
        left: 24,
        width: Math.min(viewportWidth - 48, 520),
        height: 160,
      };
  const overlayBlocks = [
    { top: 0, left: 0, width: viewportWidth, height: highlight.top },
    { top: highlight.top, left: 0, width: highlight.left, height: highlight.height },
    {
      top: highlight.top,
      left: highlight.left + highlight.width,
      width: Math.max(0, viewportWidth - highlight.left - highlight.width),
      height: highlight.height,
    },
    {
      top: highlight.top + highlight.height,
      left: 0,
      width: viewportWidth,
      height: Math.max(0, viewportHeight - highlight.top - highlight.height),
    },
  ];
  const placement = getPlacement({
    ...highlight,
    bottom: highlight.top + highlight.height,
  });

  const goNext = () => {
    if (stepIndex === steps.length - 1) {
      completePageTour(location.pathname);
      return;
    }
    setStepIndex((current) => current + 1);
  };

  return (
    <div className="fixed inset-0 z-[80]">
      {overlayBlocks.map((block, index) => (
        <div
          key={`tour-mask-${index}`}
          className="fixed z-[80] bg-black/76"
          style={block}
        />
      ))}
      <div
        className="pointer-events-none fixed z-[90] rounded-3xl border-2 border-[var(--volt-yellow)] bg-transparent shadow-[0_0_0_9999px_rgba(0,0,0,0.55),0_0_34px_rgba(234,179,8,0.55)] transition-all duration-300"
        style={highlight}
      />
      <section
        className="tour-card-enter fixed z-[95] rounded-3xl border border-[var(--volt-yellow-border)] bg-zinc-950 p-5 text-white shadow-2xl"
        style={placement}
      >
        <div className="mb-4 flex items-start justify-between gap-4">
          <div>
            <p className="mb-1 text-xs font-bold uppercase tracking-[0.2em] text-[var(--volt-yellow)]">
              Step {stepIndex + 1} of {steps.length}
            </p>
            <h2 className="font-display text-xl font-bold text-white">{step.title}</h2>
          </div>
          <button
            type="button"
            onClick={dismissTour}
            className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl border border-zinc-800 text-zinc-400 transition-colors hover:border-red-500/40 hover:bg-red-500/10 hover:text-red-300"
            aria-label="Skip guided tour"
          >
            <X size={18} />
          </button>
        </div>
        <p className="text-sm font-semibold leading-6 text-zinc-300">{step.body}</p>

        <div className="mt-5 flex items-center justify-between gap-3">
          <button
            type="button"
            onClick={() => setStepIndex((current) => Math.max(0, current - 1))}
            disabled={stepIndex === 0}
            className="flex h-10 items-center gap-2 rounded-xl border border-zinc-800 px-4 text-sm font-bold text-zinc-300 transition-colors hover:border-zinc-600 disabled:cursor-not-allowed disabled:opacity-40"
          >
            <ChevronLeft size={16} />
            Back
          </button>
          <button
            type="button"
            onClick={dismissTour}
            className="h-10 rounded-xl px-4 text-sm font-bold text-zinc-400 transition-colors hover:text-white"
          >
            Skip tour
          </button>
          <button
            type="button"
            onClick={goNext}
            className="flex h-10 items-center gap-2 rounded-xl bg-[var(--volt-yellow)] px-4 text-sm font-bold text-black transition-colors hover:brightness-110"
          >
            {stepIndex === steps.length - 1 ? "Finish" : "Next"}
            <ChevronRight size={16} />
          </button>
        </div>
      </section>
    </div>
  );
}
