import os
from pypdf import PdfReader
from fpdf import FPDF

# Mapping of PDF files to the solar content we want to append
SOLAR_ADDITIONS = {
    "battery_storage_solutions.pdf": "\n\nSolar Integration Strategy:\nWhen combined with solar panels, battery storage becomes incredibly powerful. During the day, your solar panels often produce more energy than your home consumes. Instead of sending this surplus back to the grid at a low feed-in tariff, a battery system captures it. You can then discharge this stored solar energy at night, effectively running your home on 100% renewable solar energy 24/7 and maximizing your return on investment.",
    
    "home_appliance_efficiency.pdf": "\n\nMaximizing Solar with Appliances:\nEnergy-efficient appliances synergize perfectly with solar energy systems. By scheduling heavy-load appliances (like dishwashers, washing machines, and pool pumps) to run during peak solar production hours (typically 10 AM to 2 PM), you can directly consume the free electricity generated by your roof. This strategy, known as solar self-consumption, significantly reduces your reliance on grid electricity and speeds up the payback period of both the appliances and the solar panels.",
    
    "smart_grid_optimization.pdf": "\n\nSolar and the Smart Grid:\nSolar energy is a cornerstone of modern smart grid optimization. Distributed solar generation transforms consumers into 'prosumers' who both use and produce electricity. Smart grids can communicate with home solar inverters to balance loads, stabilize voltage, and seamlessly integrate renewable energy. By participating in Virtual Power Plant (VPP) programs, homeowners can allow the grid to draw small amounts of their solar battery storage during peak demand events, earning additional credits while supporting grid stability.",
    
    "solar_energy_basics.pdf": "\n\nAdvanced Solar Technologies:\nBeyond basic photovoltaic cells, modern solar systems incorporate advanced technologies to improve yield. Monocrystalline panels offer higher efficiency in smaller spaces compared to polycrystalline variants. Microinverters and power optimizers attach to individual panels, ensuring that shading on one panel doesn't pull down the production of the entire array. Furthermore, smart solar tracking systems can physically tilt the panels throughout the day to follow the sun's trajectory, increasing overall energy capture by up to 25%.",
    
    "time_of_use_tariffs.pdf": "\n\nSolar's Role in Time-of-Use (TOU):\nA solar energy system is the most effective tool to combat expensive Time-of-Use tariffs. Typically, peak utility rates occur in the late afternoon and early evening when solar production is ramping down. By orienting some solar panels westward, homeowners can extend their solar generation into the late afternoon, directly offsetting the most expensive grid electricity. When paired with a battery, TOU tariffs can be completely avoided by charging from solar in the morning and discharging during the expensive evening peak."
}

def update_pdfs():
    data_dir = os.path.abspath(os.path.dirname(__file__))
    
    for filename, extra_content in SOLAR_ADDITIONS.items():
        filepath = os.path.join(data_dir, filename)
        if not os.path.exists(filepath):
            print(f"Skipping {filename} - not found.")
            continue
            
        print(f"Processing {filename}...")
        
        # Read existing PDF text
        reader = PdfReader(filepath)
        text = ""
        for page in reader.pages:
            text += page.extract_text() + "\n"
            
        # Append solar content
        new_text = text.strip() + extra_content
        
        # Create new PDF
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Arial", size=11)
        
        # write the title
        title = filename.replace(".pdf", "").replace("_", " ").title()
        pdf.set_font("Arial", 'B', 16)
        pdf.cell(0, 10, title, ln=True, align='C')
        pdf.ln(10)
        
        pdf.set_font("Arial", size=11)
        pdf.multi_cell(0, 6, new_text)
        
        # Overwrite the PDF
        pdf.output(filepath)
        print(f"Updated {filename} successfully.")

if __name__ == "__main__":
    update_pdfs()
