from .templates import (
    ADVISOR_AGENT_INSTRUCTION,
    ANALYST_AGENT_INSTRUCTION,
    CHAT_PROMPT_TEMPLATE,
    DEVICE_AGENT_INSTRUCTION,
    DEVICE_AGENT_USER_CONTEXT_TEMPLATE,
    ORCHESTRATOR_AGENT_INSTRUCTION,
    QA_PROMPT_TEMPLATE,
    JUDGE_PROMPT,
)

__all__ = [
    "ADVISOR_AGENT_INSTRUCTION",
    "ANALYST_AGENT_INSTRUCTION",
    "CHAT_PROMPT_TEMPLATE",
    "DEVICE_AGENT_INSTRUCTION",
    "DEVICE_AGENT_USER_CONTEXT_TEMPLATE",
    "ORCHESTRATOR_AGENT_INSTRUCTION",
    "QA_PROMPT_TEMPLATE",
    "JUDGE_PROMPT",
]
